import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/components/provider/QueryProvider";
import Header from "@/components/rootLayout/header";
import { ToastContainer } from "react-toastify";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

export const metadata: Metadata = {
  title: "Monico",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
      </head>
      <body className={`antialiased font-pretendard`}>
        <QueryProvider>
          <Header />
          {children}
          <ToastContainer
            position="top-center"
            autoClose={2000}
            hideProgressBar={true}
            stacked={true}
            limit={3}
          />
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
        </QueryProvider>
      </body>
    </html>
  );
}
