import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/components/provider/QueryProvider";
import { ToastContainer } from "react-toastify";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { ThemeProvider } from "next-themes";
import Header from "@/components/rootLayout/Header";

export const metadata: Metadata = {
  title: "Monico",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/favicon/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
      </head>
      <body className={`antialiased font-pretendard`}>
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
          >
            <Header />
            {children}
            <ToastContainer
              position="top-center"
              autoClose={2000}
              hideProgressBar={true}
              stacked={true}
              limit={3}
            />
            <ReactQueryDevtools initialIsOpen={false} />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
